FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
RUN mkdir -p /profiler-output
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-venv \
    pipx \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/root/.local/bin:$PATH"
COPY dist/*.whl /app/dist/
RUN pipx install /app/dist/*.whl --force

RUN pipx install vllm
RUN pipx inject vllm torch-c-dlpack-ext
ENTRYPOINT ["inference_profiler", "-o", "/profiler-output", "-t", "1000"]
CMD ["vllm", "serve", "/app/model/", "--gpu-memory-utilization=0.7", "--max-model-len=2048", "--dtype=bfloat16"]